name: Bot de Publicacion CampusLA

on:
  workflow_dispatch:

jobs:
  publicar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Ejecutar Robot
        run: |
          echo "Despertando el bot de Clase Mundial de CampusLA..."
          echo "¡Proceso iniciado exitosamente!"
